### ISSUE TITLE
Test spec differs from lab instruction

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/twitter-api-todo#1]
User: Ezra Smyser

Batch: web-0615

Current Lesson: Twitter API Todo

Location: https://learn.co/tracks/web-development-ruby/ruby/beginning-object-orientation/twitter-api-todo?track_id=3273&batch_id=64

Bug Description: The first test in the spec asks you to find your most recent follower, but the answer is your most recent "friend" - which is the last person you followed, not the last person to follow you (i.e. a follower, as per the API docs).

**Comment by BenjaGross** [comment]
addressed in pull request #3
