### ISSUE TITLE
end statements?

### ISSUE THREAD

**Issue by adamjonas** [learn-co-curriculum/twitter-api-todo#15]
User: Muhammad Umer

Batch: bk-003

Current Lesson: Twitter API Todo

Location: https://learn.co/tracks/web-development-fellowship/ruby/beginning-object-orientation/twitter-api-todo?track_id=1564&batch_id=132

Bug Description: https://github.com/learn-co-students/twitter-api-todo-bk-003/blob/master/spec/twitter_spec.rb after line 35 there should be two more end statements

**Comment by deniznida** [comment]
was fixed by @MsUzoAgu
