### ISSUE TITLE
remote build can't pass since this relies on secrets in a .gitignored file

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/twitter-api-todo#4]
not sure what we should do about this, but this test suite cannot pass remotely since it requires reading twitter api keys out of `application.yml` which is git ignored (and rightly so).

this may require a re-think

cc @jmburges @aviflombaum

**Comment by jmburges** [comment]
Whoever works on this. Stub out all the internet requests.

**Comment by SophieDeBenedetto** [comment]
@jmburges i'm working on it, will stub out api calls in the test suite.
